version: "3.9"

services:

  webapp-svelte.dev:
    container_name: webapp-svelte.dev
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ".:/app"
      - "/app/node_modules"
    ports:
      - 4202:4202
    environment:
      - CHOKIDAR_USEPOLLING=true